apiVersion: apps/v1
kind: Deployment
metadata:
  name: minivehicle
spec:
  selector:
    matchLabels:
      app: minivehicle
  replicas: 1
  template:
    metadata:
      labels:
        app: minivehicle

    spec:
      containers:
      - name: minivehicle
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
        resources:
          requests:
            memory: 200Mi
            cpu: 50m



---

apiVersion: v1
kind: Service

metadata:
  name: minivehicle

spec:
  selector:
    app: minivehicle

  ports:
    - name: http
      port: 8080
     



  type:  ClusterIP
